//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groubel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMember
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int UserId { get; set; }
        public int SenderId { get; set; }
        public System.DateTime Date { get; set; }
        public bool Agree { get; set; }
        public string Avatar { get; set; }
        public int Status { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
