//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groubel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat()
        {
            this.ChatComments = new HashSet<ChatComment>();
            this.ChatInterests = new HashSet<ChatInterest>();
            this.ChatMembers = new HashSet<ChatMember>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsRoom { get; set; }
        public string Name { get; set; }
        public bool Visibility { get; set; }
        public bool Anonimus { get; set; }
        public string Image { get; set; }
        public bool IsArchive { get; set; }
        public int MaxUsers { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatComment> ChatComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatInterest> ChatInterests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMember> ChatMembers { get; set; }
    }
}
