//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groubel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int SenderUserId { get; set; }
        public int ReciverUserId { get; set; }
        public int Type { get; set; }
        public bool SeenStatus { get; set; }
        public bool ApproovedStatus { get; set; }
        public int AliasId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Anonimus { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
